GoGreen/Models/ErrorViewModel.cs
using System;

namespace GoGreen.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GoGreen/Models/NotificationModel.cs
namespace GoGreen.Models
{
    public class NotificationModel
    {
        public NotificationModel()
        {
        }

        public string Status { get; set; }

        public string Message { get; set; }
    }
}

GoGreen/Models/ProduceViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace GoGreen.Models
{
    public class ProduceViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:n2}", ApplyFormatInEditMode = true)]
        [Range(0.0, Double.MaxValue, ErrorMessage = "The field {0} must be greater than {1}.")]
        public decimal? Price { get; set; }

        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "Negative {0} is not supported.")]
        public int? Stock { get; set; }
    }
}

GoGreen/Controllers/HomeController.cs
using GoGreen.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GoGreen.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GoGreen/Controllers/ProduceController.cs
using CommonLib.Produce;
using CommonLib.Services;
using GoGreen.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GoGreen.Controllers
{
    public class ProduceController : Controller
    {
        private readonly ILogger<ProduceController> _logger;

        private readonly GreenAPIService _greenApiService;

        public ProduceController(
            ILogger<ProduceController> logger,
            GreenAPIService greenApiService
        )
        {
            _logger = logger;
            _greenApiService = greenApiService;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<ProduceDTO> produce = await _greenApiService.GetAll();

            return View("Index", produce);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("ManageProduce", new ProduceViewModel());
        }

        public async Task<IActionResult> Edit(int id)
        {
            ProduceDTO produce = await _greenApiService.Get(id);

            return View("ManageProduce", new ProduceViewModel()
            {
                Id = produce.Id,
                Name = produce.Name,
                Price = produce.Price,
                Stock = produce.Stock,
            });
        }

        [HttpPost]
        public async Task<IActionResult> Save(ProduceViewModel model)
        {
            if(ModelState.IsValid)
            {
                ProduceDTO response = await _greenApiService.Save(new ProduceDTO()
                {
                    Id = model.Id,
                    Name = model.Name,
                    Price = model.Price.GetValueOrDefault(0),
                    Stock = model.Stock.GetValueOrDefault(0),
                });

                model.Id = response.Id;

                if (model.Id == 0)
                {
                    AddNotification("danger", "Save Failed!");
                }
                else
                {
                    AddNotification("success", "Save Succeeded!");
                }
            }

            return View("ManageProduce", model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            int delete = await _greenApiService.Delete(id);

            if (delete == 0)
            {
                AddNotification("danger", "Delete Failed!");
            }
            else
            {
                AddNotification("success", "Delete Succeeded!");
            }

            return await Index();
        }

        private void AddNotification(string status, string message)
        {
            if(ViewBag.Notifications == null)
            {
                ViewBag.Notifications = new List<NotificationModel>();
            }

            ViewBag.Notifications.Add(new NotificationModel()
            {
                Status = status,
                Message = message,
            });
        }
    }
}

GoGreen/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Produce Management site.</h1>
    <p></p>
</div>
<div class="text-center">
    <h1 class="display-4">Produce Tab</h1>
    <p>Please click produce next to home in the menu bar at the top. </p>
    <p>Success and Delete actions will appear in a notification at the top. </p>
    <p>Any validation errors are in an info colored panel. </p>
</div>

GoGreen/Views/Produce/Index.cshtml
@using CommonLib.Produce
@model IEnumerable<ProduceDTO>

@{
    ViewData["Title"] = "Produce Overview";
}

<div class="text-center">
    <h1 class="display-4">GoGreen! Produce Overview</h1>
    @if (Model != null)
    {
        <h2>There is $@Model.Sum(x => x.Price * x.Stock).ToString("n2") worth of inventory.</h2>
    }
    <p><a class="btn btn-primary" asp-area="" asp-controller="Produce" asp-action="Create">Add</a></p>
</div>


<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Stock</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
            foreach (ProduceDTO produce in Model)
            {
                <tr>
                    <td>@produce.Name</td>
                    <td>@produce.Price</td>
                    <td>@produce.Stock</td>
                    <td>
                        <a class="btn btn-primary" asp-area="" asp-controller="Produce" asp-action="Edit" asp-route-id="@produce.Id">Edit</a>
                        <a class="btn btn-danger" asp-area="" asp-controller="Produce" asp-action="Delete" asp-route-id="@produce.Id">Delete</a>
                    </td>
                </tr>
            }
    </tbody>
</table>

GoGreen/Views/Produce/ManageProduce.cshtml
@model ProduceViewModel

@{
    ViewData["Title"] = Model.Id > 0 ? "Manage Produce" : "Create Produce";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
</div>

<form asp-controller="Produce" asp-action="Save" method="post">
    @Html.ValidationSummary(false, null, new { @class = "alert alert-info" })
    <div class="row">
        @if (Model.Id > 0)
        {
            @Html.HiddenFor(x => x.Id)
            <div class="col-6">
                @Html.LabelFor(m => m.Id, new { @class = "float-right" })
            </div>
            <div class="col-6">
                @Html.DisplayTextFor(m => m.Id)
            </div>
        }
        <div class="col-6 float-right">
            @Html.LabelFor(m => m.Name, new { @class = "float-right" })
        </div>
        <div class="col-6">
            @Html.TextBoxFor(m => m.Name)
        </div>
        <div class="col-6 float-right">
            @Html.LabelFor(m => m.Price, new { @class = "float-right" })
        </div>
        <div class="col-6">
            @Html.TextBoxFor(m => m.Price)
        </div>
        <div class="col-6 float-right">
            @Html.LabelFor(m => m.Stock, new { @class = "float-right" })
        </div>
        <div class="col-6">
            @Html.TextBoxFor(m => m.Stock)
        </div>
        <div class="col-6 pt-1">
            <input type="submit" class="btn btn-primary float-right" />
        </div>
        <div class="col-6 pt-1">
            @Html.ActionLink("Cancel", "Index", "Produce", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

GoGreen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GoGreen!</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GoGreen!</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produce" asp-action="Index">Produce</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="text-center">
                <p>
                    @if (ViewBag.Notifications != null)
                    {
                        foreach (NotificationModel note in ViewBag.Notifications)
                        {
                            <div class="alert alert-@(note.Status)" role="alert">
                                @note.Message
                            </div>
                        }
                    }
                </p>
            </div>

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GoGreen!
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>